openapi: 3.0.3
info:
  title: Fan Engage API
  version: 0.4.0
servers:
  - url: http://localhost:8000

paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: ok
  /matches:
    get:
      summary: List matches
      responses:
        '200':
          description: List of matches
  /ingest/video:
    post:
      summary: Upload a match video (MP4)
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title: { type: string }
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Ingested
  /analyze/detections:
    get:
      summary: Run detection + tracking for a match (synchronous MVP)
      parameters:
        - in: query
          name: match_id
          required: true
          schema: { type: integer }
      responses:
        '200':
          description: Detection job result (uploaded artifact key)
          content:
            application/json:
              schema:
                type: object
                properties:
                  match_id: { type: integer }
                  key: { type: string, description: "MinIO key to Parquet (detections/match_<id>/match_<id>.parquet)" }
  /matches/{match_id}/detections:
    get:
      summary: Get detections for a match (YOLO + ByteTrack)
      parameters:
        - in: path
          name: match_id
          required: true
          schema: { type: integer }
      responses:
        '200':
          description: Array of detection records
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Detection'
  /teams/assign:
    post:
      summary: Assign team_id to player tracks for a match
      description: >
        Computes team assignments from jersey embeddings + color histograms and
        persists `tracks/match_{id}/match_{id}.parquet` to object storage.
      parameters:
        - in: query
          name: match_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Assignment summary
          content:
            application/json:
              schema:
                type: object
                properties:
                  match_id: { type: integer }
                  tracks: { type: integer }
                  by_team:
                    type: object
                    additionalProperties:
                      type: integer
                required: [match_id, tracks]
              examples:
                ok:
                  value:
                    match_id: 14
                    tracks: 12
                    by_team: { "1": 6, "2": 6 }
        '500':
          description: Assignment failed
  /matches/{match_id}/tracks:
    get:
      summary: Get team assignments (tracks) for a match
      parameters:
        - in: path
          name: match_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: List of track assignments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Track'
              examples:
                sample:
                  value:
                    - match_id: 14
                      object_id: 7
                      team_id: 1
                      n_samples: 8
                    - match_id: 14
                      object_id: 12
                      team_id: 2
                      n_samples: 8
        '404':
          description: Tracks parquet not found
  /homography/estimate:
    post:
      summary: Estimate pitch homography for a match
      description: >
        Runs pitch keypoint detector on frames, fits RANSAC homography per segment,
        and writes JSON files under homography/match_{id}/seg_XXX.json.
      parameters:
        - in: query
          name: match_id
          required: true
          schema: { type: integer }
        - in: query
          name: segment_frames
          schema: { type: integer, default: 250 }   # ~10s at 25fps
        - in: query
          name: step
          schema: { type: integer, default: 5 }     # sample every N frames
        - in: query
          name: conf_th
          schema: { type: number, default: 0.5 }    # keypoint confidence threshold
      responses:
        '200':
          description: Summary
          content:
            application/json:
              schema:
                type: object
                properties:
                  match_id: { type: integer }
                  segments: { type: integer }
                  written: { type: integer }
  /matches/{match_id}/homography:
    get:
      summary: List homography segments for a match
      parameters:
        - in: path
          name: match_id
          required: true
          schema: { type: integer }
      responses:
        '200':
          description: Array of segments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HomographySegment'
        '404':
          description: No homography found
components:
  schemas:
    Detection:
      $ref: "./schemas/detection.schema.json"
    Track:
      $ref: "./schemas/track.schema.json"
    HomographySegment:
      $ref: "./schemas/homography.schema.json"
